# -*- coding: utf-8 -*-
"""bgrep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Rjuq6mbTl3ajsJ3xGp_YMqm6tbeXXvy

PRODUCT 1
"""

!pip install Pillow
!pip install rembg Pillow
from rembg import remove
from PIL import Image

input_path = 'product1.jpg'
output_path = 'output.png'
background_path = 'shaving.jpg'
final_output_path = 'final_output.png'
with open(input_path, 'rb') as i:
    with open(output_path, 'wb') as o:
        input_data = i.read()
        output_data = remove(input_data)
        o.write(output_data)
foreground = Image.open(output_path)
background = Image.open(background_path)
background = background.resize(foreground.size)
background.paste(foreground, (0, 0), foreground)
background.save(final_output_path)
background.show()

"""PRODUCT 2"""

!pip install Pillow
!pip install rembg Pillow
from rembg import remove
from PIL import Image

input_path = 'product2.jpg'
output_path = 'output2.png'
background_path = 'ring.jpeg'
final_output_path = 'final_output1.png'
with open(input_path, 'rb') as i:
    with open(output_path, 'wb') as o:
        input_data = i.read()
        output_data = remove(input_data)
        o.write(output_data)
foreground = Image.open(output_path)
background = Image.open(background_path)
background = background.resize(foreground.size)
background.paste(foreground, (0, 0), foreground)
background.save(final_output_path)
background.show()

"""PRODUCT 3"""

!pip install Pillow
!pip install rembg Pillow
from rembg import remove
from PIL import Image

input_path = 'product3.jpg'
output_path = 'output3.png'
background_path = 'aftershave.jpeg'
final_output_path = 'final_output2.png'
with open(input_path, 'rb') as i:
    with open(output_path, 'wb') as o:
        input_data = i.read()
        output_data = remove(input_data)
        o.write(output_data)
foreground = Image.open(output_path)
background = Image.open(background_path)
background = background.resize(foreground.size)
background.paste(foreground, (0, 0), foreground)
background.save(final_output_path)
background.show()

"""PRODUCT 4"""

!pip install Pillow
!pip install rembg Pillow
from rembg import remove
from PIL import Image

input_path = 'product4.jpg'
output_path = 'output4.png'
background_path = 'shoes.jpeg'
final_output_path = 'final_output3.png'
with open(input_path, 'rb') as i:
    with open(output_path, 'wb') as o:
        input_data = i.read()
        output_data = remove(input_data)
        o.write(output_data)
foreground = Image.open(output_path)
background = Image.open(background_path)
background = background.resize(foreground.size)
background.paste(foreground, (0, 0), foreground)
background.save(final_output_path)
background.show()

"""PRODUCT 5"""

!pip install Pillow
!pip install rembg Pillow
from rembg import remove
from PIL import Image

input_path = 'product5.jpg'
output_path = 'output5.png'
background_path = 'camera.jpg'
final_output_path = 'final_output4.png'
with open(input_path, 'rb') as i:
    with open(output_path, 'wb') as o:
        input_data = i.read()
        output_data = remove(input_data)
        o.write(output_data)
foreground = Image.open(output_path)
background = Image.open(background_path)
background = background.resize(foreground.size)
background.paste(foreground, (0, 0), foreground)
background.save(final_output_path)
background.show()